export const ICON_COLOR: string = '#131117'
export const ACTIVE_COLOR: string = '#6347EB'
export const INACTIVE_COLOR: string = '#AEABC2'
export const WHITE_COLOR: string = '#FFFFFF'
export const BG_COLOR: string = '#FCFCFD'
export const LIGHT_GRAY_COLOR: string = '#EAE9F0'
export const SECONDAYR_COLOR: string = '#F46040'
export const TEXT_COLOR: string = '#2C2646'

export const GREEN_COLOR: string = '#31B447'